name: Build and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.0

    - name: Checkout the repository
      uses: actions/setup-node@v4.0.4
      with:
        node-version: '22.9.0'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Upload artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: build
        path: build
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Github Pages
        uses: actions/configure-pages@v5.0.0

      - name: Download artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: build
  
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: build
          token: ${{ secrets.GITHUB_TOKEN }}
      

