name: Publish

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.0
    - name: Checkout the repository
      uses: actions/setup-node@v4.0.4
      with:
        node-version: '22.9.0'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
